apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  ports:
  - port: 53
    name: pihole-dns-tcp
    protocol: TCP
    targetPort: 53
  - port: 53
    name: pihole-dns-udp
    protocol: UDP
    targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
